package blah;
import javax.jws.WebService;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cjones' at '25/09/18 20:45' with Gradle 2.13
 *
 * @author cjones, @date 25/09/18 20:45
 */

@WebService
public interface Library {
    public String hello(String helloMessage);
}
