package blah;
import org.junit.Test;
import static org.junit.Assert.*;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Endpoint;
import javax.xml.ws.Service;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'cjones' at '25/09/18 20:45' with Gradle 2.13
 *
 * @author cjones, @date 25/09/18 20:45
 */
public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() throws MalformedURLException {
    	 Endpoint endpoint = Endpoint.publish("http://localhost:8080/library", new LibraryImpl());
    	    assertTrue(endpoint.isPublished());
    	    assertEquals("http://schemas.xmlsoap.org/wsdl/soap/http", endpoint.getBinding().getBindingID());
    	    
    	    URL wsdlDocumentLocation = new URL("http://localhost:8080/library?wsdl");
    	    String namespaceURI = "http://blah/";
    	    String servicePart = "LibraryImplService";
    	    String portName = "LibraryImplPort";
    	    QName serviceQN = new QName(namespaceURI, servicePart);
    	    QName portQN = new QName(namespaceURI, portName);
    	    
    	    Service service = Service.create(wsdlDocumentLocation, serviceQN);
    	    Library library = service.getPort(portQN, Library.class);
    	    String msg = library.hello("hello");
    	    assertEquals("Service message: hello", msg);
    }
}
